import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import localFont from 'next/font/local';

import type { Metadata } from "next";
import "./globals.css";

const AvenirNext = localFont({
  src: [
    {
      path: '../../public/AvenirNext-Regular.woff2',
    },
    {
      path: '../../public/AvenirNext-Bold.woff2',
      weight: 'bold',
    },
  ],
})

export const metadata: Metadata = {
  title: "ToDo-Liste",
  description: "Generated by backendBanditen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
